### ISSUE TITLE
Error when enabling plugin in blender

### ISSUE THREAD

**Issue by mandar1jn** [OpenAWE-Project/BlenderNorthlight#1]
I copied the io_mesh_northlight folder into my blender addon folder, but whenever I try to enable it I get the following error:
![image](https://github.com/OpenAWE-Project/BlenderNorthlight/assets/49076509/99c5e9d8-eb92-4052-baf2-e9450ae5dfb3)
is this something on my side?

**Comment by Nostritius** [comment]
Hi, I see the problem, it seems that I forgot to remove some invalid imports. It should be fixed now. Could you test this and tell me if it works now?

**Comment by mandar1jn** [comment]
It loads now. Thank you very much. I did however find another issue #2
