### ISSUE TITLE
Both import options prompt foliage import

### ISSUE THREAD

**Issue by mandar1jn** [OpenAWE-Project/BlenderNorthlight#2]
It seems like both import options try to import a foliage file. Not only do binfbx files not show up when using the correct import button, manually dragging a binfbx file prompts a "unsupported binfol version" error

**Comment by mandar1jn** [comment]
![image](https://github.com/OpenAWE-Project/BlenderNorthlight/assets/49076509/6e6deac3-8b04-4ce3-96ae-8ad542faf8f4)

**Comment by Nostritius** [comment]
Both importers shared the same id, which led to that bug. It should now be fixed, could you test this and report if it works?

**Comment by mandar1jn** [comment]
Thank you very much, it does indeed register both correctly now. Most files seem to give an LOD error though. But some work.
![image](https://github.com/OpenAWE-Project/BlenderNorthlight/assets/49076509/257044ab-2453-489a-850f-89216c3d829f)
This might be my custom tool not exporting correctly though

**Comment by Nostritius** [comment]
May I ask, which meshes from the games you are trying to load? So I can check if it works on my end.

**Comment by mandar1jn** [comment]
it seems like every model in "data\objects\doors\" (at least as far as I check) has the error

**Comment by Nostritius** [comment]
I assume, you took the models from Quantum Break? Because the support for this files is relatively new, and there are still many unknown fields in them. I will look into that.

**Comment by mandar1jn** [comment]
They are indeed from quantum break

**Comment by Nostritius** [comment]
I think I fixed the problem in the last commit. It seems that the doors use a new vertex integer type which is not related to animation and still uses byte sized ids while normal bone ids in Quantum Break use short sized ids. Can you test if this works for you?

**Comment by mandar1jn** [comment]
it works now. Thank you very much
